# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""sov_ai_dynamic probe.

Probes the assistant for locale-specific topical breadth using a
per-locale category taxonomy. Structurally inverse of ``sov_ai_facts``:
there is **no curated question** to inject verbatim — turn 1 is
generated by the user-LLM in the persona's voice, anchored to one
``(category, subtopic_hint)`` pair from the taxonomy. The standard
user-judge gate fires on the generated turn-1.

Built on ``BaseProbe`` + ``BankBackedProbe``; the substrate handles
taxonomy load + cache + placeholder warning +
``provenance.bank_version[locale]`` pinning. ``ConversationLoop``
drives the turn loop with shared guardrails (fourth-wall prefilter,
user-judge gate retries, role-violation telemetry, frustration).

Note on shape: this probe does NOT use ``BankVerbatimMixin`` because
turn-1 is generated. The taxonomy-templated opening (persona +
invitation + subtopic_hint) is supplied via ``get_user_system_prompt``
— the user-LLM gets all context in the system message, then the
standard ``USER_QUERY_INSTRUCTION`` triggers turn-1 generation. The
plan's reference to ``CustomTurn1InstructionMixin`` was a guideline;
the actual probe doesn't need it because the existing prompt design
already carries persona + topic context in a single system message
(splitting across system + user-instruction would change behavior
without measurable benefit).

Side channels emitted on the trajectory:

- ``state.metadata["probing_categories_explored"]`` — list of
  category ids probed (today always ``[category.id]``).
- ``state.metadata["probing_subtopic_hints_used"]`` — list of
  sub-topic hint strings.
- ``state.metadata["taxonomy_id"]`` / ``taxonomy_version`` — for
  scorer reload + reporter stratification.
- ``result["probe_variant"]`` = ``category.id`` (per-row discriminator).
- ``result["probing_categories_explored"]`` /
  ``result["probing_subtopic_hints_used"]`` — top-level columns the
  scorer reads.
- ``SimulationOutcome.provenance.bank_version["<locale>"]`` —
  taxonomy version (locale-keyed; ``BankBackedProbe`` substrate
  handles via ``bank_version_key=None``).
- ``SimulationOutcome.warnings`` —
  ``WarningKind.USED_PLACEHOLDER_TAXONOMY`` appended whenever the
  taxonomy carried ``placeholder: true`` (substrate-driven).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any

from usersim.engine.core.behavioral import get_conversation_language
from usersim.engine.core.outcomes import WarningKind
from usersim.engine.core.persona import format_persona_for_prompt
from usersim.engine.core.probes import (
    BankBackedProbe,
    register_probe,
)
from usersim.engine.core.probing_taxonomy import (
    Category,
    load_probing_taxonomy_for_locale,
    reset_probing_taxonomy_cache,
)
from usersim.engine.core.simulation import (
    ConversationState,
    language_instruction,
    make_failed,
)
from usersim.engine.probes.sov_ai_dynamic.prompts import (
    PromptsUnavailableError,
    get_followup_instruction,
    get_opening_prompt,
)
from usersim.engine.probes.sov_ai_dynamic.task_derivation import (
    derive_probe,
)

logger = logging.getLogger("usersim.engine")

# ── Probe metadata ────────────────────────────────────────────────────
# Bumping ``PROMPT_VERSION`` invalidates prior evaluator rows on
# re-run, since the dedup key includes it. Bump on any semantic change
# to the user-agent prompts (or to the follow-up instruction).

PROBE_FAMILY: str = "sov_ai_dynamic"
# Probe discriminator is the picked category's id (e.g.
# ``brazil-history``). Because the category is only known after
# ``derive_probe`` runs, the probe overrides ``probe_variant`` to the
# category id in ``build_result_extras``. The dispatcher seeds
# ``probe_variant = "default"`` initially; that seed is reflected in
# ``trajectory_id`` but the final parquet row carries the real
# discriminator.
PROBE_VARIANTS: list[str] = ["default"]
PROMPT_VERSION: str = "v1.0"

# ---------------------------------------------------------------------------
# Taxonomy-loading aliases (parallel to sov_ai_facts / sov_ai_multilingual_parity)
# ---------------------------------------------------------------------------

_load_taxonomy_for_locale = load_probing_taxonomy_for_locale
_reset_taxonomy_cache = reset_probing_taxonomy_cache


def _bank_loader(locale: str):
    """Indirection through the module-level alias for test patchability."""
    return _load_taxonomy_for_locale(locale)


def should_succeed(state: ConversationState) -> bool:
    """Sim-side guardrail: did we actually probe a category?

    Returns ``False`` when the trajectory carries no probed
    categories (a structural invariant violation — derive_probe
    returned ``None`` *and* the probe still produced a record).
    Module-level mirror of the probe method so existing test
    surfaces can call this directly without an instance.
    """
    return bool(state.metadata.get("probing_categories_explored"))


class SovAiDynamicProbeError(ValueError):
    """Raised when the probe cannot construct (no category, missing prompts).

    The shim ``simulate_sov_ai_dynamic`` catches this and returns
    a structured ``make_failed`` outcome with
    ``failure_class=SCENARIO_ABORTED``.
    """


@dataclass
class _PickedProbe:
    """Substrate-shaped wrapper around the (category, subtopic_hint, taxonomy)
    triple ``derive_probe`` returns, so ``BankBackedProbe`` substrate
    can drive the placeholder-warning pipeline.

    Carries:

    - ``id`` — category.id (used by ``build_result_extras``).
    - ``placeholder`` — taxonomy.placeholder (the placeholder flag
      lives on the whole taxonomy, not per-category, so the
      substrate's ``_emit_placeholder_warning`` reads it from here).
    - ``category`` / ``subtopic_hint`` — the actual probe content.
    - ``bank_id`` / ``bank_version`` — pinned for the placeholder
      warning detail string.
    """

    id: str
    placeholder: bool
    category: Category
    subtopic_hint: str
    bank_id: str
    bank_version: str


# ---------------------------------------------------------------------------
# Probe class
# ---------------------------------------------------------------------------


@register_probe(family=PROBE_FAMILY, prompt_version=PROMPT_VERSION, variants=tuple(PROBE_VARIANTS))
class SovAiDynamicProbe(BankBackedProbe):
    """Population-probing dynamic-coverage probe.

    Generate-and-gate turn-1 (user-LLM produces the opening question
    in the persona's voice, anchored to a category invitation +
    subtopic hint); user-LLM follow-up with the locale-specific
    persona role-play prompt + per-turn follow-up instruction. The
    standard user-judge gate fires on the generated turn-1.
    """

    label = "sov_ai_dynamic"
    bank_loader = staticmethod(_bank_loader)
    placeholder_warning_kind = WarningKind.USED_PLACEHOLDER_TAXONOMY
    bank_version_key = None  # locale-keyed (the inclusion convention)

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        # Fail-fast contract: ``derive_probe`` returns None when every
        # category is excluded; effectively impossible with the shipped
        # 5-category taxonomies but reported as SCENARIO_ABORTED if it
        # ever happens.
        if self._task is None:
            raise SovAiDynamicProbeError(
                f"no usable category in {self._bank.taxonomy_id} "
                f"v{self._bank.taxonomy_version} for locale={self._locale}"
            )
        try:
            # Resolve prompts against the ASSET locale (en_IN for an India
            # variant reusing the en_IN taxonomy), not the conversation
            # locale. en_IN is a shipped pack key so this never aborts.
            # available_locales() is untouched.
            opening_template = get_opening_prompt(self._asset_locale)
            self._followup_instruction = get_followup_instruction(self._asset_locale)
        except PromptsUnavailableError as e:
            raise SovAiDynamicProbeError(str(e)) from e
        # Format the persona-grounded opening prompt once. The same
        # formatted text serves as the user-LLM's system prompt for
        # both turn-1 generation AND any follow-up turns.
        self._user_system_prompt = opening_template.format(
            persona=format_persona_for_prompt(self._persona),
            invitation=self._task.category.invitation,
            subtopic_hint=self._task.subtopic_hint,
        )
        # For an India variant the opening prompt fell back to the en_IN
        # (English) pack, which does NOT tell the user-agent which language
        # to write turn-1 in. Unlike the general probes (whose templates
        # carry a {language_instruction} slot) and unlike follow-up turns
        # (which the loop steers via get_conversation_language), turn-1 here
        # is generated straight from this system prompt — so without an
        # explicit directive the agent writes English and the deterministic
        # script gate rejects every attempt (USER_LANGUAGE_GATE_EXHAUSTED).
        # Append the native/romanized language directive for variants only;
        # shipped locales keep their in-language pack byte-for-byte.
        if self._asset_locale != self._locale:
            directive = language_instruction(get_conversation_language(self._locale), self._locale)
            if directive:
                self._user_system_prompt = f"{self._user_system_prompt}\n\n{directive}"

    # ── BankBackedProbe API ─────────────────────────────────────────

    def derive_task(
        self,
        persona: dict[str, Any],
        bank: Any,
        *,
        cfg: Any,
    ) -> _PickedProbe | None:
        """Pick the matched category + subtopic_hint for this persona.

        Returns None when ``derive_probe`` finds no usable category
        — the substrate skips placeholder-warning / version-pin in
        that case and ``__init__`` raises.
        """
        result = derive_probe(persona, bank, seed=getattr(cfg, "random_seed", None))
        if result is None:
            return None
        category, subtopic_hint = result
        return _PickedProbe(
            id=category.id,
            placeholder=bool(getattr(bank, "placeholder", False)),
            category=category,
            subtopic_hint=subtopic_hint,
            bank_id=bank.taxonomy_id,
            bank_version=bank.taxonomy_version,
        )

    # ── ProbeAdapter required hooks ─────────────────────────────────

    def get_user_system_prompt(self) -> str:
        return self._user_system_prompt

    def get_assistant_system_prompt(self) -> str:
        # Pure-capability-test policy.
        return ""

    # ── Optional hooks ──────────────────────────────────────────────

    def seed_state_metadata(self, state: ConversationState) -> None:
        """Pre-seed side-channel metadata before turn-1 logic runs.

        This probe doesn't use verbatim turn-1 (turn-1 is generated
        + gated), so it can't rely on the
        ``get_verbatim_first_user_turn(state)`` side-effect pattern
        that ``sov_ai_facts`` uses. ``seed_state_metadata`` is the
        path-agnostic equivalent: ``ConversationLoop.run`` calls it
        immediately after constructing state, both verbatim and
        generate-and-gate paths preserve the seeded keys via
        ``setdefault``.
        """
        if self._task is None:
            return
        state.metadata["probing_categories_explored"] = [self._task.category.id]
        state.metadata["probing_subtopic_hints_used"] = [self._task.subtopic_hint]
        state.metadata["taxonomy_id"] = self._task.bank_id
        state.metadata["taxonomy_version"] = self._task.bank_version

    async def format_followup_user_instructions(
        self,
        turn_idx: int,
        state: ConversationState,
    ) -> list[str]:
        if not self._followup_instruction:
            return []
        return [self._followup_instruction]

    def should_succeed(self, state: ConversationState) -> bool:
        return should_succeed(state)

    def build_result_extras(self, state: ConversationState) -> dict:
        extras = super().build_result_extras(state)
        if self._task is not None:
            extras["probe_variant"] = self._task.category.id
            # Top-level columns the sov_ai_dynamic scorer reads directly.
            extras["probing_categories_explored"] = list(state.metadata.get("probing_categories_explored") or [])
            extras["probing_subtopic_hints_used"] = list(state.metadata.get("probing_subtopic_hints_used") or [])
        return extras


# ---------------------------------------------------------------------------
# Override BankBackedProbe._pin_bank_version for taxonomy attribute name
# ---------------------------------------------------------------------------
# The substrate's default ``_pin_bank_version`` reads ``bank.bank_version``
# but the ProbingTaxonomy uses ``taxonomy_version``. Override.


def _pin_bank_version_override(self, locale: str) -> None:
    """Pin ``provenance.bank_version[locale]`` from the taxonomy."""
    bank_version = getattr(self._bank, "taxonomy_version", None)
    if bank_version is None:
        return
    key = type(self).bank_version_key or locale
    self._provenance.bank_version[key] = bank_version


SovAiDynamicProbe._pin_bank_version = _pin_bank_version_override  # type: ignore[method-assign]


# ---------------------------------------------------------------------------
# Public entry point — thin shim around SovAiDynamicProbe
# ---------------------------------------------------------------------------


async def simulate_sov_ai_dynamic(
    models: dict[str, Any],
    data: dict[str, Any],
    persona: dict[str, Any],
    profile: dict[str, Any],
    locale: str,
    language: str,
    cfg: Any,
    **kwargs: Any,
) -> dict[str, Any]:
    """Thin shim for callers that import ``simulate_sov_ai_dynamic``.

    Catches construction exceptions (taxonomy-load / no-usable-category
    / prompt-pack-missing) and returns a ``make_failed`` outcome with
    ``failure_class=SCENARIO_ABORTED``.
    """
    from usersim.engine.core.outcomes import OutcomeBuilder
    from usersim.engine.core.outcomes import Provenance as _Provenance
    from usersim.engine.core.probes import BankLoadError

    provenance = kwargs.get("provenance") or _Provenance()
    outcome_builder = kwargs.get("outcome_builder") or OutcomeBuilder(
        provenance=provenance,
    )
    try:
        probe = SovAiDynamicProbe(
            persona=persona,
            locale=locale,
            language=language,
            models=models,
            cfg=cfg,
            provenance=provenance,
            profile=profile,
            data=data,
            outcome_builder=outcome_builder,
        )
    except BankLoadError as e:
        return _aborted(
            f"probing-taxonomy load failed for locale={locale}: {e}",
            provenance,
        )
    except SovAiDynamicProbeError as e:
        return _aborted(str(e), provenance)
    return await probe.run_dispatch(models=models, data=data, cfg=cfg)


def _aborted(reason: str, provenance: Any) -> dict[str, Any]:
    """Build a structured SCENARIO_ABORTED failure result."""
    from usersim.engine.core.outcomes import (
        FailureAttribution,
        FailureClass,
        OutcomeBuilder,
        OutcomeStatus,
    )
    from usersim.engine.core.outcomes import (
        Provenance as _Provenance,
    )

    builder = OutcomeBuilder(provenance=provenance or _Provenance())
    outcome = builder.finalize(
        status=OutcomeStatus.FAILED,
        failure_class=FailureClass.SCENARIO_ABORTED,
        failure_attribution=FailureAttribution.SCENARIO_LOGIC,
        failure_detail=reason,
    )
    return make_failed(reason, outcome=outcome, traces=[])
