# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NVIDIA-Software-and-Model-Evaluation

"""Probe template — bank-anchored generated turn-1.

Use this shape when turn-1 should be GENERATED by the user-LLM in
the persona's voice, but ANCHORED to a bank-derived hint (e.g., a
category, a sub-topic, an exploration angle). The
``sov_ai_dynamic`` probe uses this shape — it picks a category
+ sub-topic-hint deterministically and lets the user-agent compose
an opening question in-voice.

Why not ``BankVerbatimMixin``?
- Verbatim is wrong here: paraphrasing through the persona's voice
  is the FEATURE (it surfaces what real users in this cohort would
  organically ask). Verbatim would re-introduce benchmark
  contamination.

Why not ``CustomTurn1InstructionMixin``?
- That mixin hands the user-LLM a separate turn-1 instruction through
  ``get_user_query_instruction``, which suits an opening that asks for
  something the rest of the conversation does not. ``sov_ai_dynamic``
  and this template keep persona, invitation and subtopic hint in a
  single system message instead, which serves every turn alike.

What you provide:
- ``derive_task(persona, bank, *, cfg)`` — picks the bank entry.
- ``__init__(...)`` — formats the persona-grounded opening prompt
  once, stores it on ``self``.
- ``get_user_system_prompt`` — returns the formatted opening prompt.
- ``seed_state_metadata(state)`` — populates side-channel metadata
  PATH-AGNOSTICALLY (called before turn-1 path branching, so it
  works for both verbatim and generate-and-gate).
- ``format_followup_user_instructions(turn_idx, state)`` — optional
  per-follow-up nudge.
- ``should_succeed(state)`` + ``build_result_extras(state)`` — same
  as the bank_verbatim shape.

Total LOC: ~100. ``sov_ai_dynamic`` is a real example at ~280 LOC.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from usersim.engine.core.outcomes import WarningKind
from usersim.engine.core.probes import BankBackedProbe, register_probe


@dataclass
class _DemoCategory:
    id: str
    placeholder: bool
    invitation: str
    subtopic_hint: str


def _demo_taxonomy_loader(locale: str = "en_US"):
    raise NotImplementedError("replace with your real taxonomy loader")


@register_probe(
    family="demo_custom_turn1",
    prompt_version="v1.0",
    variants=("default",),
)
class DemoCustomTurn1Probe(BankBackedProbe):
    """Bank-anchored, generated-in-voice turn-1 probe."""

    label = "demo_custom_turn1"
    bank_loader = staticmethod(_demo_taxonomy_loader)
    placeholder_warning_kind = WarningKind.USED_PLACEHOLDER_TAXONOMY
    bank_version_key: str | None = None  # locale-keyed

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        if self._task is None:
            raise ValueError("no resolvable category")
        # Format the opening user-agent prompt ONCE (persona-grounded,
        # bank-anchored). The user-LLM generates turn-1 against this
        # prompt; subsequent turns use the same prompt + nudge.
        self._opening_prompt = self._format_opening()

    def _format_opening(self) -> str:
        return (
            f"You are a real user from {self._locale}. "
            f"In your own voice, ask a question about "
            f"'{self._task.subtopic_hint}'. "
            f"Invitation framing: {self._task.invitation}"
        )

    def derive_task(
        self,
        persona: dict,
        bank: Any,
        *,
        cfg: Any,
    ) -> _DemoCategory | None:
        return _DemoCategory(
            id="cat-demo",
            placeholder=True,
            invitation="Tell me about",
            subtopic_hint="demo subtopic",
        )

    def get_user_system_prompt(self) -> str:
        return self._opening_prompt

    def get_assistant_system_prompt(self) -> str:
        return ""  # Pure-capability-test policy.

    def seed_state_metadata(self, state: Any) -> None:
        # Path-agnostic seeding — called by ConversationLoop BEFORE
        # the verbatim-vs-generate path branches. setdefault preserves
        # any keys a verbatim helper might have already written.
        state.metadata.setdefault("probing_categories_explored", [self._task.id])
        state.metadata.setdefault(
            "probing_subtopic_hints_used",
            [self._task.subtopic_hint],
        )

    async def format_followup_user_instructions(
        self,
        turn_idx: int,
        state: Any,
    ) -> list[str]:
        return [
            "Continue the conversation naturally — ask one follow-up "
            "question that goes deeper into the same topic, in your voice."
        ]

    def should_succeed(self, state: Any) -> bool:
        return bool(state.metadata.get("probing_categories_explored"))

    def build_result_extras(self, state: Any) -> dict:
        extras = super().build_result_extras(state)
        # Every key added here must also be listed in
        # ConversationSimulatorConfig.side_effect_columns, or the engine
        # discards it on the way to storage and the scorer reads it back
        # as absent.
        if self._task is not None:
            extras["probe_variant"] = self._task.id
            extras["probing_categories_explored"] = list(state.metadata.get("probing_categories_explored") or [])
            extras["probing_subtopic_hints_used"] = list(state.metadata.get("probing_subtopic_hints_used") or [])
        return extras
